### ISSUE TITLE
Unexpected end of archive error when unzipping with 7z

### ISSUE THREAD

**Issue by mli43** [WebQnA/WebQA#11]
## Error summary
I encountered this issue of "Unexpected end of archive error" when unzipping with 7z. I cloned this repo and followed the instructions. This error happened after running the ```download_imgs.sh``` file and confirming all 51 chunks and the ```imgs.lineidx``` file is present in the directory. All our attempts have failed on three different platforms including windows, AWS ubuntu, and GCP ubuntu. The error message looks like:

![image](https://github.com/WebQnA/WebQA/assets/49251962/8c1aae4a-de62-4153-a227-aefd6c647aec)

### Attempt 1: windows local
- Platform: Windows 11 Home
- Disk: 300+ GB free storage
- 7z Version: V22.01 (x64)
<img width="203" alt="image" src="https://github.com/WebQnA/WebQA/assets/49251962/598a054c-0d8b-47bd-ad5c-91cf843c4828">

### Attempt 2: linux local
- Platform: Windows WSL Ubuntu
- Disk: 300+ GB free storage
- 7z version: V16.02
<img width="801" alt="image" src="https://github.com/WebQnA/WebQA/assets/49251962/5f6144b5-2e90-4162-b3ff-2bf49bc43114">

### Attempt 3: AWS
System specs: 
- Deep Learning AMI GPU CUDA 11.1.1 (Ubuntu 18.04) 20230405
- Image ID: ami-01b901ded27bef504
![image](https://github.com/WebQnA/WebQA/assets/49251962/c5cfcfad-93d8-4b04-93ea-8a6aced8f132)
![image](https://github.com/WebQnA/WebQA/assets/49251962/8ef64d2d-0903-402a-baf4-0c304b74090b)
![image](https://github.com/WebQnA/WebQA/assets/49251962/1f64f9d6-4527-4ca6-bbbd-90670ebac1ee)

### Attempt 4: GCP
System specs:
![image](https://github.com/WebQnA/WebQA/assets/49251962/168de6e2-94d4-4594-a0e5-b4e913b2808f)
![image](https://github.com/WebQnA/WebQA/assets/49251962/bddae1bc-ba00-411e-8586-4472249c411a)
![image](https://github.com/WebQnA/WebQA/assets/49251962/730cf5d1-357a-4aec-8bbd-921f684110f8)

## Lastly
I put the the attempt details in hope that it can be recreated. I wonder if this issue has to do with the 7z version or the downloading script being maybe not up to date.

**Comment by zdxdsw** [comment]
Can you try removing .lineidx from the current directory and try again?

**Comment by mli43** [comment]
I tried putting the only the chunks into one folder and still shows the same error. This is for WSL.
<img width="986" alt="image" src="https://github.com/WebQnA/WebQA/assets/49251962/5af2d6ba-6cd6-4028-b752-0764642b891f">

**Comment by zdxdsw** [comment]
uhm Maybe the header file is corrupted. Try redownload `.001`?

**Comment by mli43** [comment]
I believe the file is successfully downloaded. We also re-ran the bash script multiple times. Each time it is downloading and terminating correctly.
<img width="1227" alt="image" src="https://github.com/WebQnA/WebQA/assets/49251962/fe2be581-e354-4a0f-8f63-ad137410c1c0">

**Comment by mli43** [comment]
I looked at the downloading again and noticed this error. I think this might be causing the problem. I believe this is a problem with the source download?
![image](https://github.com/WebQnA/WebQA/assets/49251962/fb68e0ae-348c-4367-ad4a-29abc9ae8805)

**Comment by zdxdsw** [comment]
Hi! 
Thanks for locating the problem. It seems that our server refuses the connection. Please try downloading from google drive https://drive.google.com/drive/folders/1ApfD-RzvJ79b-sLeBx1OaiPNUYauZdAZ?usp=sharing

**Comment by SnowNation101** [comment]
Did u solve this? I encountered the same error here. I downloaded all 51 chunks from the google drive and put only these 51 chunks in a single folder, but still cant extract them with 7z.

**Comment by mli43** [comment]
Hi. I checked the bash downloading script. It looks like it's running the same download command on different chunks. I ran the bash script and ran the command separately for chunks that are missing. Then I could unzip with 7z.

**Comment by SnowNation101** [comment]
> Hi. I checked the bash downloading script. It looks like it's running the same download command on different chunks. I ran the bash script and ran the command separately for chunks that are missing. Then I could unzip with 7z.

the bash seems not working now, cant connect to the server.

**Comment by mli43** [comment]
> > Hi. I checked the bash downloading script. It looks like it's running the same download command on different chunks. I ran the bash script and ran the command separately for chunks that are missing. Then I could unzip with 7z.
> 
> the bash seems not working now, cant connect to the server.

Oh that's interesting. Is it not working for all of the chunks or for a few? If it's for all chunks then I'd suggest contacting the repo owner.

**Comment by SnowNation101** [comment]
thank u, i'll ask this in a new issue!
