### ISSUE TITLE
Dataset json file doesn't have "Keywords_A" for any question.

### ISSUE THREAD

**Issue by Abhiram4572** [WebQnA/WebQA#5]
`Webqa_train_val.json`
For any query, Keywords_A is missing. 
But I see this key as part of your baseline evaluation and also Take_a_look_WebQA.ipynb files,
Kindly help with this, please share a data version that has this key, so that we can evaluate our models better.

**Comment by WebQnA** [comment]
Hi!

The keyword_a field is only for evaluation purposes. We only collected
keywords for the testing data and, unfortunately, it is hidden.

If you want to reproduce the keyword extraction process on val data, we
would suggest you try named entity detection and noun-chunk extraction
tools with Spacy.

Thanks for the question!
